name: Manual Apply Terraform to Prod

on:
  workflow_dispatch:

jobs:
  apply-preprod:
    uses: ./.github/workflows/tf-apply-manual-shared.yml
    with:
      workspace: prod
      var-file: prod.tfvars