name: Terraform Apply with Approval

on:
  push:
    branches:
      - main
      - preprod
      - test-pr-a
    paths:
      - '**/*.tf'
  workflow_dispatch:

jobs:
  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::127350417158:role/github_oidc_role
          aws-region: us-east-1

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Ensure Terraform Workspace Exists
        run: |
          terraform workspace list | grep -q "${{ github.ref_name == 'main' && 'prod' || 'preprod' }}" \
          || terraform workspace new ${{ github.ref_name == 'main' && 'prod' || 'preprod' }}

      - name: Select Terraform Workspace
        run: terraform workspace select ${{ github.ref_name == 'main' && 'prod' || 'preprod' }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -var-file=${{ github.ref_name == 'main' && 'prod' || 'preprod' }}.tfvars -out=tfplan

      - name: Upload Terraform Plan
        uses: actions/upload-artifact@v3
        with:
          name: tfplan
          path: tfplan

  terraform-apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    needs: terraform-plan
    if: github.event_name == 'workflow_dispatch'

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::127350417158:role/github_oidc_role
          aws-region: us-east-1

      - name: Download Terraform Plan
        uses: actions/download-artifact@v3
        with:
          name: tfplan

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Select Terraform Workspace
        run: terraform workspace select ${{ github.ref_name == 'main' && 'prod' || 'preprod' }}

      - name: Terraform Apply
        run: terraform apply tfplan

      - name: Clean up
        run: rm tfplan
