name: Terraform Apply with Manual Approval

on:
  workflow_dispatch: # Allows manual triggering of the workflow
    inputs:
      environment:
        description: 'Select the environment to apply (preprod or prod)'
        required: true
        default: 'preprod'
        type: choice
        options:
          - preprod
          - prod

jobs:
  terraform-apply:
    name: Terraform Apply
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }} # Ensures the correct branch is checked out

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::127350417158:role/github_oidc_role
          aws-region: us-east-1

      - name: Clean Terraform Cache
        run: rm -rf .terraform

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform Init with Upgrade
        run: terraform init -upgrade

      - name: Ensure Terraform Workspace Exists
        run: |
          terraform workspace list | grep -q "${{ github.event.inputs.environment }}" \
          || terraform workspace new ${{ github.event.inputs.environment }}

      - name: Select Terraform Workspace
        run: terraform workspace select ${{ github.event.inputs.environment }}

      - name: Terraform Plan
        run: terraform plan -var-file=${{ github.event.inputs.environment }}.tfvars -out=tfplan

      - name: Terraform Apply
        run: terraform apply -input=false tfplan

      - name: Clean up
        run: rm tfplan
