name: Terraform Apply with Approval

on:
  push:
    branches:
      - main
      - preprod
      - test-pr-a
    paths:
      - '**/*.tf'

jobs:
  terraform:
    name: Terraform Apply
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::127350417158:role/github_oidc_role
          aws-region: us-east-1

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Ensure Terraform Workspace Exists
        run: |
          terraform workspace list | grep -q "${{ github.ref_name == 'main' && 'prod' || 'preprod' }}" \
          || terraform workspace new ${{ github.ref_name == 'main' && 'prod' || 'preprod' }}

      - name: Select Terraform Workspace
        run: terraform workspace select ${{ github.ref_name == 'main' && 'prod' || 'preprod' }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -var-file=${{ github.ref_name == 'main' && 'prod' || 'preprod' }}.tfvars -out=tfplan

      - name: Request Manual Approval
        uses: juliangruber/approve-pull-request-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          number: 1
          title: 'Approve Terraform Apply for ${{ github.ref_name == 'main' && 'prod' || 'preprod' }}'
          body: 'Approve the apply of the planned changes for ${{ github.ref_name == 'main' && 'prod' || 'preprod' }} workspace.'

      - name: Terraform Apply
        if: ${{ steps.approval.outputs.approval_result == 'approve' }}
        run: terraform apply tfplan

      - name: Clean up
        run: rm tfplan
