name: Terraform Apply with Approval

on:
  push:
    branches:
      - preprod
      - prod
    paths:
      - '**/*.tf'

jobs:
  terraform:
    name: Terraform Apply
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Select Terraform Workspace
        run: terraform workspace select ${{ github.ref_name }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -var-file=${{ github.ref_name }}.tfvars -out=tfplan

      - name: Request Manual Approval
        uses: flyway/approve-pull-request-action@v1.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          title: 'Approve Terraform Apply for ${{ github.ref_name }}'
          body: 'Approve the apply of the planned changes for ${{ github.ref_name }} workspace.'

      - name: Terraform Apply
        if: ${{ steps.approval.outputs.approval_result == 'approve' }}
        run: terraform apply tfplan

      - name: Clean up
        run: rm tfplan
