name: Shared PR Close Triggered Terraform Apply

on:
  workflow_call:
    inputs:
      workspace:
        description: 'The Terraform workspace to use'
        type: string
        required: true
      var-file:
        description: 'The Terraform variable file to use'
        type: string
        required: true
      stack:
        description: 'The directory containing the Terraform configuration'
        type: string
        required: true

jobs:
  terraform-apply:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::127350417158:role/github_oidc_role-role
          aws-region: us-east-1

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Change to Terraform directory
        run: cd ${{ inputs.stack }}

      - name: Terraform Init
        run: terraform init

      - name: Select Workspace
        run: terraform workspace select ${{ inputs.workspace }}

      - name: Terraform Plan
        run: terraform plan -var-file=${{ inputs.var-file }} -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan