name: Terraform Apply main on PR merge to main

on:
  push:
    branches:
      - main
    paths:
      - "**/*.tf"

jobs:
  terraform-apply:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: write  # Ensure write access to create a PR
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}  # Use a PAT with repo scope

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::127350417158:role/github_oidc_role
          aws-region: us-east-1

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        run: terraform init
      
      - name: Select prod Workspace
        run: terraform workspace new prod

      - name: Terraform Plan
        run: terraform plan -var-file=prod.tfvars -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan