name: Terraform Apply Non-Main Branch

on:
  push:
    branches-ignore:
      - main
    paths:
      - '**/*.tf'

jobs:
  terraform-apply:
    name: Terraform Apply
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }} 

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::127350417158:role/github_oidc_role-role
          aws-region: us-east-1

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        run: terraform init

      - name: Select preprod Workspace
        run: terraform workspace new preprod
      
      - name: Terraform Plan
        run: terraform plan -var-file=preprod.tfvars -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan