name: Terraform Apply main on PR merge to main

on:
  pull_request:
    types: [closed]
    branches:
      - main
    paths:
      - "**/*.tf"

jobs:
  apply-preprod:
    if: github.event.pull_request.merged == true
    uses: ./.github/workflows/tf-apply-shared.yml
    with:
      workspace: preprod
      var-file: preprod.tfvars
  
  apply-prod:
    if: github.event.pull_request.merged == true
    uses: ./.github/workflows/tf-apply-shared.yml
    with:
      workspace: prod
      var-file: prod.tfvars
