name: Create PR with Terraform Plan

on:
  pull_request:
    paths:
      - '**/*.tf'

jobs:
  create-pr:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: write  # Ensure write access to create a PR
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}  # Use a PAT with repo scope

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::127350417158:role/github_oidc_role
          aws-region: us-east-1

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        id: plan
        run: terraform plan -out=tfplan

      - name: Add Terraform Plan to PR
        id: add-plan
        run: |
          terraform show -no-color tfplan > plan.txt
          cat plan.txt
      
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            This PR contains the Terraform plan for the changes in .tf files.
            ```${{ steps.add-plan.outputs.stdout }}```