name: Push to non-main branch
on:
  push:
    branches: [main]
      # - "main"
# TODO: Locking mechanism to prevent multiple deployments at the same time
# TODO: Add a way to notify the user of the deployment status
# I created a new role, which had policy that allowed me to do this
# I need to understand what has been done, organize the roles
jobs:
  build:
    name: deploy
    runs-on: ubuntu-latest
    environment: dev

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::127350417158:role/github_oidc_role
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: |
          docker build -t hello-world .

      # - name: Tag Docker image
      #   run: |
      #     docker tag hello-world:latest ${{ steps.login-ecr.outputs.registry }}/${{ github.repository }}:latest
      - name: Tag Docker image
        run: |
          IMAGE_URI=${{ steps.login-ecr.outputs.registry }}/${{ github.repository }}:latest
          echo "IMAGE_URI=${IMAGE_URI}" >> $GITHUB_ENV

      - name: Push Docker image to ECR
        run: |
            docker push ${{ steps.login-ecr.outputs.registry }}/${{ github.repository }}:latest
        
      - name: Echo the image URI
        run: |
          echo "Docker image has been pushed to ECR: $IMAGE_URI"


      # - name: Increment value
      #   uses: yoichiro/gh-action-increment-value@main
      #   with:
      #     target_directory: "."
      #     target_file: "build_number.json"
      #     prefix: 'buildNumber":'
      #     suffix: "}"
      #     commit_message: "Increment the build number to "

  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Run a one-line script
  #       run: echo Hello, world!

  # notify:
  #   runs-on: ubuntu-latest
  #   needs: deploy
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Run a one-line script
  #       run: echo Hello, world!
