name: Push to non-main branch
on:
  push:
    branches:
      [main]
      # - "main"
# TODO: Locking mechanism to prevent multiple deployments at the same time
# TODO: Add a way to notify the user of the deployment status
# I created a new role, which had policy that allowed me to do this
# I need to understand what has been done, organize the roles

env:
  AWS_REGION: MY_AWS_REGION                    # set this to your preferred AWS region, e.g. us-west-1
  ECR_REPOSITORY: quanta-test                  # set this to your Amazon ECR repository name
  ECS_SERVICE: MY_ECS_SERVICE                  # set this to your Amazon ECS service name
  ECS_CLUSTER: MY_ECS_CLUSTER                  # set this to your Amazon ECS cluster name
  ECS_TASK_DEFINITION: MY_ECS_TASK_DEFINITION  # set this to the path to your Amazon ECS task definition
                                               # file, e.g. .aws/task-definition.json
  CONTAINER_NAME: MY_CONTAINER_NAME            # set this to the name of the container in the
                                               # containerDefinitions section of your task definition
jobs:
  build:
    name: deploy
    runs-on: ubuntu-latest
    environment: dev

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::127350417158:role/github_oidc_role
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        # with:
          # registry: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com
          # registry: 127350417158.dkr.ecr.us-east-1.amazonaws.com

      - name: Build Docker image
        run: |
          docker build -t hello-world .

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          # Build a docker container and
          # push it to ECR so that it can
          # be deployed to ECS.
          echo "ECR_REGISTRY=$ECR_REGISTRY"
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Echo the image URI
        run: |
          echo "Docker image has been pushed to ECR: $IMAGE_URI"

      # - name: Increment value
      #   uses: yoichiro/gh-action-increment-value@main
      #   with:
      #     target_directory: "."
      #     target_file: "build_number.json"
      #     prefix: 'buildNumber":'
      #     suffix: "}"
      #     commit_message: "Increment the build number to "

  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Run a one-line script
  #       run: echo Hello, world!

  # notify:
  #   runs-on: ubuntu-latest
  #   needs: deploy
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Run a one-line script
  #       run: echo Hello, world!
